<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602082459 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_EMAIL ON app_user (email)');
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, icon_url VARCHAR(255) DEFAULT NULL, points INT DEFAULT 0 NOT NULL, description TEXT DEFAULT NULL, awarded_by VARCHAR(100) DEFAULT NULL, awarded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FEF0481DCB944F1A ON badge (student_id)');
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, logo_url VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094FA76ED395 ON company (user_id)');
        $this->addSql('CREATE TABLE offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, location VARCHAR(255) DEFAULT NULL, is_remote BOOLEAN DEFAULT false NOT NULL, salary_min NUMERIC(8, 2) DEFAULT NULL, salary_max NUMERIC(8, 2) DEFAULT NULL, expires_at DATE DEFAULT NULL, starts_at DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_29D6873E979B1AD6 ON offer (company_id)');
        $this->addSql('CREATE TABLE offer_skill (offer_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (offer_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_DD10999E53C674EE ON offer_skill (offer_id)');
        $this->addSql('CREATE INDEX IDX_DD10999E5585C142 ON offer_skill (skill_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, repo_url VARCHAR(255) DEFAULT NULL, demo_url VARCHAR(255) DEFAULT NULL, image_urls JSON DEFAULT NULL, is_public BOOLEAN DEFAULT true NOT NULL, completion_year SMALLINT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EECB944F1A ON project (student_id)');
        $this->addSql('CREATE TABLE project_skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, project_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D68EDE9166D1F9C ON project_skill (project_id)');
        $this->addSql('CREATE INDEX IDX_4D68EDE95585C142 ON project_skill (skill_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROJECT_SKILL ON project_skill (project_id, skill_id)');
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, category VARCHAR(50) NOT NULL, icon_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SKILL_NAME ON skill (name)');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, bio TEXT DEFAULT NULL, avatar_url VARCHAR(255) DEFAULT NULL, github_url VARCHAR(255) DEFAULT NULL, linkedin_url VARCHAR(255) DEFAULT NULL, promotion_year INT DEFAULT NULL, score INT DEFAULT 0 NOT NULL, is_visible BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B723AF33A76ED395 ON student (user_id)');
        $this->addSql('CREATE TABLE student_skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(20) NOT NULL, years_of_experience INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D60A9DEACB944F1A ON student_skill (student_id)');
        $this->addSql('CREATE INDEX IDX_D60A9DEA5585C142 ON student_skill (skill_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STUDENT_SKILL ON student_skill (student_id, skill_id)');
        $this->addSql('ALTER TABLE badge ADD CONSTRAINT FK_FEF0481DCB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offer ADD CONSTRAINT FK_29D6873E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offer_skill ADD CONSTRAINT FK_DD10999E53C674EE FOREIGN KEY (offer_id) REFERENCES offer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE offer_skill ADD CONSTRAINT FK_DD10999E5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EECB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_skill ADD CONSTRAINT FK_4D68EDE9166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_skill ADD CONSTRAINT FK_4D68EDE95585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student_skill ADD CONSTRAINT FK_D60A9DEACB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student_skill ADD CONSTRAINT FK_D60A9DEA5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE badge DROP CONSTRAINT FK_FEF0481DCB944F1A');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094FA76ED395');
        $this->addSql('ALTER TABLE offer DROP CONSTRAINT FK_29D6873E979B1AD6');
        $this->addSql('ALTER TABLE offer_skill DROP CONSTRAINT FK_DD10999E53C674EE');
        $this->addSql('ALTER TABLE offer_skill DROP CONSTRAINT FK_DD10999E5585C142');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EECB944F1A');
        $this->addSql('ALTER TABLE project_skill DROP CONSTRAINT FK_4D68EDE9166D1F9C');
        $this->addSql('ALTER TABLE project_skill DROP CONSTRAINT FK_4D68EDE95585C142');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33A76ED395');
        $this->addSql('ALTER TABLE student_skill DROP CONSTRAINT FK_D60A9DEACB944F1A');
        $this->addSql('ALTER TABLE student_skill DROP CONSTRAINT FK_D60A9DEA5585C142');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE offer');
        $this->addSql('DROP TABLE offer_skill');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_skill');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE student_skill');
    }
}
